routes/admin.php
<?php
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admin\{
    AdminCommentController,
    AdminContactController,
    AdminProjectCategoryController,
    AdminProjectController,
    AdminSliderController,
    MenuController,
    AdminSliderItemController,
    AdminPostCategoryController,
    AdminPostController,
    AdminController,
    AdminLandCategoryController,
    AdminLandController,

};

use App\Http\Controllers\Auth\AuthController;


Route::get('login',[AuthController::class,'index'])->name('admin.login.index');
Route::post('check',[AuthController::class,'login'])->name('admin.login.check');

Route::middleware('auth:web')->group(function(){
    Route::get('logout',[AuthController::class,'logout'])->name('admin.logout');
    Route::get('/',[AdminController::class, 'index'])->name('admin.home');

    Route::prefix('category-post')->group(function(){
        Route::get('/',[AdminPostCategoryController::class,'index'])->name('admin.category-post.index');
        Route::get('/add',[AdminPostCategoryController::class,'add'])->name('admin.category-post.add');
        Route::post('/create',[AdminPostCategoryController::class,'create'])->name('admin.category-post.create');
        Route::get('/edit/{id}',[AdminPostCategoryController::class,'edit'])->name('admin.category-post.edit');
        Route::post('/update/{id}',[AdminPostCategoryController::class,'update'])->name('admin.category-post.update');
        Route::get('/delete/{id}',[AdminPostCategoryController::class,'delete'])->name('admin.category-post.delete');

    });

    Route::prefix('post')->group(function(){
        Route::get('/',[AdminPostController::class,'index'])->name('admin.post.index');
        Route::get('/add',[AdminPostController::class,'add'])->name('admin.post.add');
        Route::post('/create',[AdminPostController::class,'create'])->name('admin.post.create');
        Route::get('/edit/{id}',[AdminPostController::class,'edit'])->name('admin.post.edit');
        Route::post('/update/{id}',[AdminPostController::class,'update'])->name('admin.post.update');
        Route::get('/delete/{id}',[AdminPostController::class,'delete'])->name('admin.post.delete');

    });

    Route::prefix('project-category')->group(function(){
        Route::get('/',[AdminProjectCategoryController::class,'index'])->name('admin.project-category.index');
        Route::get('/add',[AdminProjectCategoryController::class,'add'])->name('admin.project-category.add');
        Route::post('/create',[AdminProjectCategoryController::class,'create'])->name('admin.project-category.create');
        Route::get('/edit/{id}',[AdminProjectCategoryController::class,'edit'])->name('admin.project-category.edit');
        Route::post('/update/{id}',[AdminProjectCategoryController::class,'update'])->name('admin.project-category.update');
        Route::get('/delete/{id}',[AdminProjectCategoryController::class,'delete'])->name('admin.project-category.delete');

    });

    Route::prefix('project')->group(function(){
        Route::get('/',[AdminProjectController::class,'index'])->name('admin.project.index');
        Route::get('/add',[AdminProjectController::class,'add'])->name('admin.project.add');
        Route::post('/create',[AdminProjectController::class,'create'])->name('admin.project.create');
        Route::get('/edit/{id}',[AdminProjectController::class,'edit'])->name('admin.project.edit');
        Route::post('/update/{id}',[AdminProjectController::class,'update'])->name('admin.project.update');
        Route::get('/delete/{id}',[AdminProjectController::class,'delete'])->name('admin.project.delete');

    });

    Route::prefix('land-category')->group(function(){
        Route::get('/',[AdminLandCategoryController::class,'index'])->name('admin.land-category.index');
        Route::get('/add',[AdminLandCategoryController::class,'add'])->name('admin.land-category.add');
        Route::post('/create',[AdminLandCategoryController::class,'create'])->name('admin.land-category.create');
        Route::get('/edit/{id}',[AdminLandCategoryController::class,'edit'])->name('admin.land-category.edit');
        Route::post('/update/{id}',[AdminLandCategoryController::class,'update'])->name('admin.land-category.update');
        Route::get('/delete/{id}',[AdminLandCategoryController::class,'delete'])->name('admin.land-category.delete');

    });

    Route::prefix('land')->group(function(){
        Route::get('/',[AdminLandController::class,'index'])->name('admin.land.index');
        Route::get('/add',[AdminLandController::class,'add'])->name('admin.land.add');
        Route::post('/create',[AdminLandController::class,'create'])->name('admin.land.create');
        Route::get('/edit/{id}',[AdminLandController::class,'edit'])->name('admin.land.edit');
        Route::post('/update/{id}',[AdminLandController::class,'update'])->name('admin.land.update');
        Route::get('/delete/{id}',[AdminLandController::class,'delete'])->name('admin.land.delete');

    });

    Route::prefix('slider')->group(function(){
        Route::get('/',[AdminSliderController::class,'index'])->name('admin.slider.index');
        Route::get('/add',[AdminSliderController::class,'add'])->name('admin.slider.add');
        Route::post('/create',[AdminSliderController::class,'create'])->name('admin.slider.create');
        Route::get('/edit/{id}',[AdminSliderController::class,'edit'])->name('admin.slider.edit');
        Route::post('/update/{id}',[AdminSliderController::class,'update'])->name('admin.slider.update');
        Route::get('/delete/{id}',[AdminSliderController::class,'delete'])->name('admin.slider.delete');

    });

    Route::prefix('slider-item')->group(function(){
        Route::get('/',[AdminSliderItemController::class,'index'])->name('admin.slider-item.index');
        Route::get('/add',[AdminSliderItemController::class,'add'])->name('admin.slider-item.add');
        Route::post('/create',[AdminSliderItemController::class,'create'])->name('admin.slider-item.create');
        Route::get('/edit/{id}',[AdminSliderItemController::class,'edit'])->name('admin.slider-item.edit');
        Route::post('/update/{id}',[AdminSliderItemController::class,'update'])->name('admin.slider-item.update');
        Route::get('/delete/{id}',[AdminSliderItemController::class,'delete'])->name('admin.slider-item.delete');

    });

    Route::prefix('menu')->group(function(){
        Route::get('/',[MenuController::class,'index'])->name('admin.menu.index');
        Route::get('/add',[MenuController::class,'add'])->name('admin.menu.add');
        Route::post('/create',[MenuController::class,'create'])->name('admin.menu.create');
        Route::get('/edit/{id}',[MenuController::class,'edit'])->name('admin.menu.edit');
        Route::post('/update/{id}',[MenuController::class,'update'])->name('admin.menu.update');
        Route::get('/delete/{id}',[MenuController::class,'delete'])->name('admin.menu.delete');

    });

    Route::prefix('contact')->group(function(){
        Route::get('/',[AdminContactController::class,'index'])->name('admin.contact.index');
        Route::get('/detail/{id}',[AdminContactController::class,'detail'])->name('admin.contact.detail');
        Route::get('/delete/{id}',[AdminContactController::class,'delete'])->name('admin.contact.delete');

    });

    Route::prefix('comment')->group(function(){
        Route::get('/',[AdminCommentController::class,'index'])->name('admin.comment.index');
        Route::get('/delete/{id}',[AdminCommentController::class,'delete'])->name('admin.comment.delete');

    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\{HomeController, WebContactController, WebLandController, WebPostController, WebProjectController};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('index');

Route::get('/gioi-thieu', [HomeController::class, 'about'])->name('about');

Route::prefix('/du-an')->group(function () {
    Route::get('/',[WebProjectController::class, 'index'])->name('project.index');
    Route::get('/{slug}', [WebProjectController::class,'detail'])->name('project.detail');
});

Route::prefix('/tin-tuc')->group(function(){
    Route::get('/',[WebPostController::class, 'index'])->name('post.index');
    Route::get('/{slug}', [WebPostController::class,'detail'])->name('post.detail');
});

Route::prefix('/dat-ban')->group(function(){
    Route::get('/',[WebLandController::class, 'index'])->name('land.index');
    Route::get('/{slug}.html', [WebLandController::class,'detail'])->name('land.detail');
});

Route::prefix('lien-he')->group(function(){
    Route::get('/',[WebContactController::class, 'index'])->name('contact.index');
    Route::post('/store',[WebContactController::class, 'store'])->name('contact.create');
});

app/Models/Contact.php
<?php


namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'email',
        'phone',
        'content',
        'is_read'
    ];
}

app/Models/PostCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class PostCategory extends Model
{
    use Sluggable;
    use HasFactory;
    protected $fillable = [
        'name',
        'slug',
        'is_active'
    ];

    public function posts(){
        return $this->hasMany(Post::class);
    }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
    public function getImageAttribute()
    {
        return $this->getFirstMediaUrl('images');
    }
}

resources/views/web/page/contact/index.blade.php
@extends('web.layout.master')
@section('title')
@endsection
@section('breadcrumb')
    @include('web.path.breadcrumb',['banner'=>getSlider('about-banner')->first()->image])
@endsection
@section('content')
    <!-- Our Agents Section Start -->
    <div class="contact-section section pt-110 pt-md-90 pt-sm-70 pt-xs-60 pb-110 pb-md-90 pb-sm-70 pb-xs-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="contact-us-wrap">
                        <div class="contact-title pb-30">
                            <h4>Liên Hệ Với <span>Chúng Tôi</span></h4>
                            <p>abc</p>
                        </div>

                        <div class="contact-info">
                            <ul>
                                <li>
                                    <div class="contact-text d-flex align-items-center">
                                        <i class="glyph-icon flaticon-placeholder"></i>
                                        <p>256, 1st AVE, Manchester <br>125 , Noth England</p>
                                    </div>
                                </li>
                                <li>
                                    <div class="contact-text d-flex align-items-center">
                                        <i class="glyph-icon flaticon-call"></i>
                                        <p>
                                            <span>Telephone : <a href="#"> +88 (012) 356 958 45</a></span>
                                            <span>Telephone : <a href="#"> +88 (012) 356 958 45</a></span>
                                        </p>
                                    </div>
                                </li>
                                <li>
                                    <div class="contact-text d-flex align-items-center">
                                        <i class="glyph-icon flaticon-earth"></i>
                                        <p>
                                            <span>Email : <a href="#">info@example.com</a></span>
                                            <span>Web : <a href="#">www.example.com</a></span>
                                        </p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="contact-us-wrap">
                        <h4>Leave a Message</h4>

                        <div class="contact-form">
                            <form id="contact-form" action="{{ route('contact.create') }} ">
                                @csrf
                                <div class="row row-10">
                                    <div class="col-md-6 col-12 mb-30"><input  name="name" type="text" placeholder="Tên" required></div>
                                    <div class="col-md-6 col-12 mb-30"><input  name="phone" type="text" placeholder="Số điện thoại" required></div>
                                    <div class="col-md-6 col-12 mb-30"><input  name="email" type="email" placeholder="Email" required></div>
                                    <div class="col-12 mb-30"><textarea name="content"  placeholder="Nội dung"></textarea></div>
                                    <div class="col-12 mb-30">{!! app('captcha')->display() !!}</div>
                                    <div class="col-12"><button class="btn send-btn btn-circle">Send</button></div>
                                </div>
                            </form>
                            <p class="form-messege"></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div><!-- Our Agents Section End -->

    <div class="embed-responsive embed-responsive-21by9">
        <div id="contact-map" class="embed-responsive-item contact-map" data-lat="40.828411" data-Long="-74.589912"></div>
    </div>
@endsection